name: antslct
channels:
    - conda-forge
dependencies:
    - click=6.7
    - funcsigs=1.0.2
    - future=0.16.0
    - jinja2=2.10
    - matplotlib=2.1.1
    - mock=2.0.0
    - nibabel=2.2.1
    - numpy=1.14.0
    - packaging=16.8
    - pandas=0.21.0
    - prov=1.5.1
    - pydot=1.2.3
    - pydotplus=2.0.2
    - pytest=3.3.2
    - python-dateutil=2.6.1
    - seaborn=0.8.1
    - scikit-learn=0.19.1
    - scipy=1.0.0
    - simplejson=3.12.0
    - traits=4.6.0
    - pip:
        - nilearn==0.3.1
        - niworkflows==0.3.1
        - svgutils==0.3.0

